#!/bin/bash
set -e

# Detect the root Btrfs partition
DEVICE=$(findmnt -n -o SOURCE /)

echo "==> Setting up Btrfs subvolumes on $DEVICE"

# Skip if subvolumes already exist (re-run safety)
if btrfs subvolume list / | grep -q '@'; then
    echo "Btrfs subvolumes already exist — skipping creation."
    exit 0
fi

btrfs subvolume create /@
btrfs subvolume create /@home
btrfs subvolume create /@log
btrfs subvolume create /@cache
btrfs subvolume create /@snapshots

umount /

echo "==> Remounting subvolumes"

mount -o subvol=@ "$DEVICE" /

mkdir -p /home
mount -o subvol=@home "$DEVICE" /home

mkdir -p /var/log
mount -o subvol=@log "$DEVICE" /var/log

mkdir -p /var/cache
mount -o subvol=@cache "$DEVICE" /var/cache

mkdir -p /.snapshots
mount -o subvol=@snapshots "$DEVICE" /.snapshots

echo "==> Writing fstab"

cat <<EOF >/etc/fstab
# /etc/fstab generated by Butter Bean Linux setup

$DEVICE / btrfs defaults,subvol=@ 0 0
$DEVICE /home btrfs defaults,subvol=@home 0 0
$DEVICE /var/log btrfs defaults,subvol=@log 0 0
$DEVICE /var/cache btrfs defaults,subvol=@cache 0 0
$DEVICE /.snapshots btrfs defaults,subvol=@snapshots 0 0

# Detect and add EFI partition (assumes /boot/efi)
$(lsblk -n -o NAME,FSTYPE,MOUNTPOINT | grep "vfat" | awk '{print "/dev/"$1" /boot/efi vfat defaults 0 1"}')

EOF

echo "==> Btrfs setup complete"
